[api]
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 17

[auth]
minimum_password_length = 12
password_requirements = "lower_upper_letters_digits_symbols"

[functions.welcome-user]
verify_jwt = false

[functions.manage-home]
verify_jwt = false

[functions.weekly-api-content-sync]
verify_jwt = false
