-- Use public.shortcuts as the source of truth for user-selected Home shortcuts.

CREATE TABLE IF NOT EXISTS public.shortcuts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  displayorder integer NOT NULL DEFAULT 0,
  activity_idactivity integer REFERENCES public.activities(id) ON DELETE CASCADE,
  scenario_idscenario integer REFERENCES public.scenarios(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.shortcuts ADD COLUMN IF NOT EXISTS displayorder integer NOT NULL DEFAULT 0;
ALTER TABLE public.shortcuts ADD COLUMN IF NOT EXISTS activity_idactivity integer;
ALTER TABLE public.shortcuts ADD COLUMN IF NOT EXISTS scenario_idscenario integer;
ALTER TABLE public.shortcuts ADD COLUMN IF NOT EXISTS user_id uuid;

CREATE INDEX IF NOT EXISTS idx_shortcuts_user_order
ON public.shortcuts (user_id, displayorder);

CREATE INDEX IF NOT EXISTS idx_shortcuts_user_activity
ON public.shortcuts (user_id, activity_idactivity)
WHERE activity_idactivity IS NOT NULL;

ALTER TABLE public.shortcuts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "p_shortcuts_select_own" ON public.shortcuts;
CREATE POLICY "p_shortcuts_select_own"
ON public.shortcuts
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "p_shortcuts_insert_own" ON public.shortcuts;
CREATE POLICY "p_shortcuts_insert_own"
ON public.shortcuts
FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "p_shortcuts_update_own" ON public.shortcuts;
CREATE POLICY "p_shortcuts_update_own"
ON public.shortcuts
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "p_shortcuts_delete_own" ON public.shortcuts;
CREATE POLICY "p_shortcuts_delete_own"
ON public.shortcuts
FOR DELETE
TO authenticated
USING (user_id = auth.uid());
