name: Supabase Check

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:

jobs:
  check-database:
    name: Check Database Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Migrations
        run: |
          echo "Verificando se as migrações estão presentes..."
          ls -R supabase/migrations/*.sql
          echo "Tudo pronto para deploy manual ou via CLI!"
